# Generated by Django 5.2.7 on 2026-01-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "genre",
            },
        ),
        migrations.CreateModel(
            name="GiftCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                ("expiration_date", models.DateField()),
            ],
            options={
                "db_table": "gift_certificate",
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45, unique=True)),
                (
                    "screen_type",
                    models.CharField(
                        choices=[
                            ("2D", "2D"),
                            ("3D", "3D"),
                            ("IMAX", "IMAX"),
                            ("4DX", "4DX"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
            options={
                "db_table": "hall",
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("duration", models.SmallIntegerField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("release_date", models.DateField()),
                ("description", models.TextField()),
                ("genres", models.ManyToManyField(to="catalog.genre")),
            ],
            options={
                "db_table": "film",
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField(db_column="row_num")),
                ("seat", models.IntegerField(db_column="seat_num")),
                (
                    "hall",
                    models.ForeignKey(
                        db_column="hall_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.hall",
                    ),
                ),
            ],
            options={
                "db_table": "seat",
                "unique_together": {("hall", "row", "seat")},
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("canceled", "Canceled"),
                            ("finished", "Finished"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        db_column="film_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.film",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        db_column="hall_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.hall",
                    ),
                ),
            ],
            options={
                "db_table": "session",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("sold", "Sold"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="booked",
                        max_length=10,
                    ),
                ),
                ("purchase_time", models.DateTimeField(auto_now_add=True)),
                (
                    "seat",
                    models.ForeignKey(
                        db_column="seat_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.seat",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.session",
                    ),
                ),
            ],
            options={
                "db_table": "ticket",
                "unique_together": {("session", "seat")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("fail", "Fail"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("refund", "Refund"),
                            ("gift_redeem", "Gift Redeem"),
                        ],
                        default="sale",
                        max_length=15,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.customer",
                    ),
                ),
                (
                    "gift_certificate",
                    models.ForeignKey(
                        blank=True,
                        db_column="gift_certificate_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.giftcertificate",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        db_column="ticket_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
