# Generated by Django 5.2.7 on 2026-01-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=9),
        ),
    ]
