# Generated by Django 5.2.7 on 2026-01-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_seat_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
